# Kernels de actividad

```{r}
load("data_processed/datos_procesados_v4.RData")

data <- data %>% 
  filter(!sp %in% c("Btau", "Cfam")) %>%  # Sacamos los datos de ganado vacuno y perros domésticos
  select(everything(), -c(lat, lon, clock, nocturnal, moon_phase, n_tech_cam, n_tech_sys, datetime))
```


Este script tiene que iterar todas las especies y variables, para crear un grafico que integra los tres niveles de la variable bajo, medio y alto. 



```{r}
bajo_umbral <- 0.33
medio_umbral <- 0.66

results_list <- list()

for (sp_ in unique(data$sp)) {
  data_filtered <- data %>% 
    filter(sp == sp_)
  
  data_result <- data_filtered %>% 
    select(site, system, camera, sp, solar)
  
  for (var in 6:ncol(data_filtered)) {
    tmp <- data_filtered %>% pull(var)
    data_result[[names(data_filtered)[var]]] <- cut(tmp, breaks = c(-Inf, bajo_umbral, medio_umbral, Inf), labels = c("Bajo", "Medio", "Alto"))
  }
  
  # Añadir el resultado de la especie actual a la lista
  results_list[[sp_]] <- data_result
}

# Combinar todos los resultados en un solo dataframe
final_result <- bind_rows(results_list)
```

```{r}
for (sp_ in unique(data$sp)) {
  data_filtered <- data %>% 
    filter(sp == sp_)
  
  for (var in 6:ncol(data_filtered)) {
    tmp <- data_filtered %>%
      filter(open_cam_lvls == "Bajo")

    low <- fitact(tmp$solar, sample="model", reps=100)
    
    tmp <- data_filtered %>%
      filter(open_cam_lvls == "Medio")
    
    mid <- fitact(tmp$solar, sample="model", reps=100)
    
    tmp <- data_filtered %>%
      filter(open_cam_lvls == "Alto")
    
    high <- fitact(tmp$solar, sample="model", reps=100) 
  }
}

```

```{r}
plot(low, yunit="density", data="none", las=1, lwd=2,
     cline=list(lty=0)) # Elimina intervalos de confianza

plot(mid, yunit="density", data="none", add=TRUE, 
     tline=list(col="red", lwd=2),
     cline=list(lty=0))
plot(high, yunit="density", data="none", add=TRUE, 
     tline=list(col="red", lwd=2),
     cline=list(lty=0))
```














```{r}
tmp <- data %>% 
  filter(sp == "Aaxi") 

m_aaxi <- fitact(tmp$solar, sample="model", reps=100)
plot(m_aaxi)
```

```{r}
tmp <- data %>% 
  filter(sp == "Mgou")

m_mgou <- fitact(tmp$solar, sample="model", reps=100)
plot(m_mgou)
```

También se pueden ver ambos en un mismo gráfico.

```{r}
plot(m_aaxi, yunit="density", data="none", las=1, lwd=2,
     tline=list(lwd=2), # Linea gruesa
     cline=list(lty=0)) # Elimina intervalos de confianza

plot(m_mgou, yunit="density", data="none", add=TRUE, 
     tline=list(col="red", lwd=2),
     cline=list(lty=0))
```
