# Kernels de actividad

```{r}
load("data_processed/datos_procesados_v4.RData")

data <- data %>% 
  filter(!sp %in% c("Btau", "Cfam")) %>%  # Sacamos los datos de ganado vacuno y perros domésticos
  select(everything(), -c(lat, lon, clock, nocturnal, moon_phase, n_tech_cam, n_tech_sys, datetime))
```


Este script tiene que iterar todas las especies y variables, para crear un grafico que integra los tres niveles de la variable bajo, medio y alto. 


```{r}
bajo_umbral <- 0.33
medio_umbral <- 0.66

results_list <- list()

for (sp_ in unique(data$sp)) {
  data_filtered <- data %>% 
    filter(sp == sp_)
  
  data_result <- data_filtered %>% 
    select(site, system, camera, sp, solar)
  
  for (var in 6:ncol(data_filtered)) {
    tmp <- data_filtered %>% pull(var)
    data_result[[names(data_filtered)[var]]] <- cut(tmp, breaks = c(-Inf, bajo_umbral, medio_umbral, Inf), labels = c("Bajo", "Medio", "Alto"))
  }
  
  # Añadir el resultado de la especie actual a la lista
  results_list[[sp_]] <- data_result
}

# Combinar todos los resultados en un solo dataframe
final_result <- bind_rows(results_list)
```

```{r}
low_color <- "#36BA98"
mid_color <- "#E9C46A"
high_color <- "#E76F51"
```

```{r eval=FALSE}
for (sp_ in unique(final_result$sp)) {
  data_filtered <- final_result %>% 
    filter(sp == sp_)
  
  for (var in 6:ncol(data_filtered)) {
    
    var_name <- colnames(data_filtered)[var]  # Obtener el nombre de la columna
    
    tmp_low <- data_filtered %>% filter(.[[var]] == "Bajo")
    tmp_mid <- data_filtered %>% filter(.[[var]] == "Medio")
    tmp_high <- data_filtered %>% filter(.[[var]] == "Alto")
    
    if(nrow(tmp_low) > 0 && nrow(tmp_mid) > 0 && nrow(tmp_high) > 0) {
      low <- fitact(tmp_low$solar, sample="model", reps=100)
      mid <- fitact(tmp_mid$solar, sample="model", reps=100)
      high <- fitact(tmp_high$solar, sample="model", reps=100)
      
      # Crear el gráfico con diferentes colores y añadir el título
      ylim_max <- max(low@pdf[,4], mid@pdf[,4], high@pdf[,4]) * 1.1

      png(filename = paste0("exports/plots/fitacts/", sp_, "-", var_name, ".png"))
      plot(low, yunit="density", data="rug", las=1, lwd=2,
           cline=list(lty=0), tline=list(col=low_color, lwd=2),
           main=paste(var_name, "-", sp_),
           ylim=c(0, ylim_max)) # Añadir título

      plot(mid, yunit="density", data="rug", add=TRUE, 
           tline=list(col=mid_color, lwd=2),
           cline=list(lty=0),
           ylim=c(0, ylim_max))
      plot(high, yunit="density", data="rug", add=TRUE, 
           tline=list(col=high_color, lwd=2),
           cline=list(lty=0),
           ylim=c(0, ylim_max))
      
      # Añadir la leyenda
      legend("topright", legend=c(paste("Bajo (n=", nrow(tmp_low), ")", sep=""), 
                                  paste("Medio (n=", nrow(tmp_mid), ")", sep=""), 
                                  paste("Alto (n=", nrow(tmp_high), ")", sep="")),
             col=c(low_color, mid_color, high_color), lwd=2, bty="n")
      
      dev.off()
      print(paste("Plot de la especie ", sp_, " y variable ", var_name, " creado."))
    } else {
      print(paste("No hay suficientes datos en alguna categoría para:", sp_, "-", var_name))
    }
  }
}
```

